/*
# Seed service_details with content for each service

1. Inserts detailed content for all 8 services
2. Each service detail includes: hero title/subtitle, overview, 4 features, 4 process steps, CTA text
*/

INSERT INTO service_details (service_id, hero_title, hero_subtitle, overview, feature_1_title, feature_1_desc, feature_2_title, feature_2_desc, feature_3_title, feature_3_desc, feature_4_title, feature_4_desc, process_title, process_step_1, process_step_2, process_step_3, process_step_4, cta_text) VALUES
('3e9bf554-f72b-4e9b-a457-5c277309ede9',
'Professional Website Development',
'Build a digital home that converts visitors into paying customers.',
'A well-designed website is the foundation of your entire digital presence. At JaspuraHub, we craft custom, responsive websites that are not just visually stunning but engineered to drive conversions. Every layout decision, every line of code, and every interaction is planned with your business goals in mind. We use modern frameworks and best practices to ensure your site loads fast, ranks well on search engines, and delivers a seamless experience across all devices.',
'Custom Design & UX',
'Every website is designed from scratch based on your brand identity and target audience. No templates, no cookie-cutter layouts—just purposeful design that guides users toward action.',
'Mobile-First Development',
'We build for mobile first and scale up, ensuring your site works flawlessly on every screen size. Over 70% of Indian web traffic is mobile—your site must be ready.',
'SEO-Ready Architecture',
'Clean code, fast load times, proper heading structures, and schema markup are baked in from day one so search engines can find and rank your content.',
'Integrated Analytics & Automation',
'Connect your site to Google Analytics, CRM systems, email marketing tools, and lead capture forms so every visitor interaction is tracked and nurtured.',
'How We Build Your Website',
'Discovery: We learn your brand, audience, competitors, and goals to create a strategic blueprint.',
'Design: Wireframes and visual mockups are created, reviewed, and refined with your feedback.',
'Development: We build with modern tech, optimize for speed and SEO, and integrate all tools.',
'Launch & Optimize: We deploy, monitor performance, and iterate based on real user data.',
'Need a website that actually grows your business? Let us build one that works as hard as you do.'),

('4396ab89-e388-4876-96b8-2263029b0b68',
'Online Ads & Media Buying',
'Maximize every rupee of your ad spend with strategic campaigns.',
'Digital advertising is the fastest way to get in front of your ideal customers—but only when done right. At JaspuraHub, we plan, execute, and optimize ad campaigns across Google, Facebook, Instagram, LinkedIn, and YouTube. Our approach is data-driven: we research your audience, craft compelling creatives, and continuously optimize to lower your cost-per-acquisition while scaling results. No wasted budget, no vanity metrics—just real ROI.',
'Full-Funnel Campaign Strategy',
'We build campaigns for every stage of the buyer journey—from awareness to consideration to conversion—so your ads reach the right people with the right message at the right time.',
'Creative Testing & Optimization',
'We A/B test ad copy, images, videos, and landing pages to find the winning combinations that drive the most conversions at the lowest cost.',
'Smart Budget Allocation',
'Our team monitors performance daily and reallocates budget to top-performing campaigns, ad sets, and audiences so your spend always works hardest.',
'Retargeting & Lookalike Audiences',
'We re-engage visitors who didn''t convert and find new customers similar to your best ones—dramatically increasing your conversion rates.',
'How We Run Your Campaigns',
'Strategy: We research your market, audience, and competitors to define targeting and messaging.',
'Launch: We set up campaigns, ad sets, creatives, and tracking pixels across platforms.',
'Optimize: Daily monitoring, A/B testing, and bid adjustments to improve performance.',
'Report: Transparent weekly and monthly reports showing exactly where your money goes and what it returns.',
'Ready to turn your ad budget into a growth engine? Let us build campaigns that deliver real results.'),

('c137f811-8707-4863-ad9d-5d66681b9769',
'Search Engine Optimization (SEO)',
'Dominate search results and drive sustainable organic traffic.',
'SEO is the long game that pays off exponentially. At JaspuraHub, we use white-hat, proven strategies to improve your search rankings, drive qualified organic traffic, and build lasting online authority. Our SEO process covers everything from technical audits to content strategy to ethical link building—ensuring your website is optimized for both search engines and real users. The result? A steady stream of qualified leads without paying for every click.',
'Technical SEO Audits',
'We crawl your site to find and fix technical issues—broken links, slow pages, crawl errors, missing schema—that hold back your rankings.',
'On-Page Optimization',
'We optimize titles, meta descriptions, headings, internal links, and content structure so every page signals relevance to search engines.',
'Content & Keyword Strategy',
'We identify high-value keywords your audience is searching for and create content that answers their questions and earns top rankings.',
'Authority & Link Building',
'We build your site''s authority through ethical, editorial-quality backlinks from relevant and trusted sources in your industry.',
'Our SEO Process',
'Audit: Comprehensive technical and content audit to identify opportunities and fix issues.',
'Strategy: Keyword research, competitive analysis, and content roadmap tailored to your goals.',
'Implementation: On-page optimization, content creation, and link building executed systematically.',
'Monitor & Refine: Monthly reporting, rank tracking, and ongoing optimization based on data.',
'Want to rank higher and get found by your ideal customers? Let us build your SEO strategy.'),

('dd0bba2d-7f0c-48b7-80df-e6dbfda88376',
'E-commerce Account Management',
'Grow your marketplace sales on Amazon, Flipkart, and beyond.',
'Selling on marketplaces is a full-time job—listing optimization, advertising, inventory management, and competitor monitoring all demand constant attention. JaspuraHub handles every aspect of your e-commerce presence so you can focus on your products and operations. From catalog setup to advertising campaigns to performance analytics, we manage your accounts end-to-end with a focus on increasing visibility, orders, and profitability.',
'Catalog & Listing Optimization',
'We create and optimize product listings with keyword-rich titles, compelling descriptions, high-quality images, and A+ content that converts shoppers into buyers.',
'Advertising & Promotions',
'We manage sponsored ads, deals, and promotional campaigns to increase visibility and drive sales while keeping ACoS within target.',
'Pricing & Rating Strategy',
'We monitor competitor pricing, optimize your price points, and implement review strategies to boost your product ratings and buy box wins.',
'Inventory & Performance Monitoring',
'We track stock levels, prevent stockouts, and monitor key metrics like order defect rate and late shipment rate to keep your account healthy.',
'How We Manage Your Accounts',
'Onboarding: We audit your current listings, analyze competitors, and set up reporting dashboards.',
'Optimization: Listings are rewritten, images improved, and advertising campaigns launched.',
'Growth: Daily monitoring, bid optimization, and promotional planning to scale orders.',
'Reporting: Weekly and monthly reviews with actionable insights and clear performance data.',
'Ready to scale your marketplace sales? Let us manage your e-commerce accounts for maximum growth.'),

('65e466b6-d2eb-4e6c-8505-f96149df3680',
'Google My Business Optimization',
'Capture local customers searching for your services in your area.',
'When someone near you searches for what you offer, your Google Business Profile is often the first thing they see. JaspuraHub optimizes your GMB profile so you show up in the local pack, Google Maps, and voice search results. We handle everything from profile setup and keyword optimization to review management and posting calendars—ensuring your local presence drives phone calls, direction requests, and website visits.',
'Profile Setup & Optimization',
'We create or claim your profile and optimize every field—business description, categories, services, attributes—with keywords your customers search for.',
'Review Management',
'We implement strategies to generate more positive reviews and respond to all feedback professionally, boosting your credibility and local rankings.',
'Local Content & Posts',
'We create and schedule Google Posts with offers, events, and updates that keep your profile active and engaging for potential customers.',
'Insights & Performance Tracking',
'We track how customers find you—search vs. maps, calls, website clicks, direction requests—and optimize based on real data.',
'Our GMB Optimization Process',
'Audit: We review your current profile, identify gaps, and benchmark against top local competitors.',
'Optimize: Every field is filled with keyword-rich, compelling content designed to rank and convert.',
'Activate: We launch a posting calendar, implement review generation, and set up messaging.',
'Monitor & Improve: Monthly performance reviews with ongoing optimization to maintain top rankings.',
'Want more local customers finding you on Google? Let us optimize your business profile.'),

('215bd8f0-5114-4f8a-be05-230e82b20f2f',
'Social Media Marketing',
'Build brand loyalty and stay top-of-mind across every platform.',
'Social media is where your audience lives—and JaspuraHub helps you meet them there with content that engages, inspires, and converts. We manage your presence across Facebook, Instagram, LinkedIn, Twitter, and more with strategic content calendars, community management, and targeted advertising. Our goal isn''t just likes and followers—it''s building a loyal community that drives real business results.',
'Content Strategy & Creation',
'We develop monthly content calendars and create scroll-stopping posts—graphics, videos, carousels, and stories—that reflect your brand voice and engage your audience.',
'Community Management',
'We respond to comments, messages, and mentions promptly to build relationships and keep your audience engaged with your brand.',
'Social Media Advertising',
'We run targeted ad campaigns on Facebook, Instagram, and LinkedIn to reach new audiences, retarget website visitors, and drive conversions.',
'Influencer & Partnership Outreach',
'We identify and connect with relevant influencers and brand partners to amplify your reach and build social proof.',
'Our Social Media Process',
'Strategy: We define your brand voice, content pillars, audience segments, and campaign goals.',
'Create: Our designers and copywriters produce content that stops the scroll and sparks engagement.',
'Publish & Engage: We post consistently and manage community interactions to grow your following.',
'Analyze & Optimize: Monthly reports with insights on reach, engagement, and conversions to refine strategy.',
'Ready to turn social media into a growth channel? Let us build your brand''s social presence.'),

('37b4e6a1-790f-428d-829e-7f64e0ccc5be',
'Content Marketing',
'Create content that attracts, educates, and converts your ideal customers.',
'Content is the engine that powers every digital marketing channel. At JaspuraHub, we create strategic content that serves your audience at every stage of their journey—from awareness-building blog posts to conversion-focused landing pages to nurturing email sequences. Our content is research-backed, SEO-optimized, and aligned with your brand voice. Every piece has a purpose: to attract the right people and guide them toward becoming customers.',
'Blog & Article Writing',
'We research and write SEO-optimized blog posts that rank on Google, answer your audience''s questions, and establish your brand as an authority.',
'Landing Page & Website Copy',
'We write conversion-focused copy for landing pages, home pages, and product pages that guides visitors toward taking action.',
'Email Sequences & Newsletters',
'We design email nurture sequences that move leads through your funnel and newsletters that keep your audience engaged and informed.',
'Content Strategy & Planning',
'We develop topic clusters, keyword-targeted content roadmaps, and publishing schedules aligned with your SEO and business goals.',
'Our Content Marketing Process',
'Research: We study your audience, competitors, and keywords to identify high-impact content opportunities.',
'Plan: We create a content calendar and strategy document with topics, formats, and distribution channels.',
'Create: Our writers and designers produce polished, on-brand content optimized for search and conversion.',
'Distribute & Measure: We publish, promote, and track performance—then refine based on what works.',
'Want content that drives traffic and converts? Let us build your content engine.'),

('da098f60-601d-4e1e-a521-3f82c1ca01be',
'Analytics & Reporting',
'Track performance with clarity and make data-driven decisions.',
'You can''t improve what you don''t measure. At JaspuraHub, we set up comprehensive tracking and reporting systems that connect your marketing activity to real business outcomes. No more vanity metrics or confusing dashboards—just clear, actionable insights that tell you exactly what''s working, what''s not, and where to invest next. We build custom dashboards, track KPIs across every channel, and deliver reports that actually help you make decisions.',
'Custom Dashboards',
'We build real-time dashboards tailored to your business—showing the metrics that matter most: revenue, leads, cost-per-acquisition, and ROI.',
'Cross-Channel KPI Tracking',
'We track performance across ads, SEO, social, email, and website so you see the full picture of how your marketing works together.',
'Conversion & Funnel Analysis',
'We map and measure your customer journey from first click to purchase, identifying drop-off points and optimization opportunities.',
'Actionable Recommendations',
'Every report includes specific, prioritized recommendations—not just data dumps—so you know exactly what to do next.',
'Our Analytics Process',
'Setup: We implement tracking pixels, GA4, conversion events, and connect all your data sources.',
'Dashboard: We build custom dashboards that surface the metrics tied to your business goals.',
'Monitor: We track performance daily and flag anomalies, trends, and opportunities in real time.',
'Report: Monthly strategy reviews with clear insights, recommendations, and next steps.',
'Want to know exactly what your marketing is delivering? Let us build your analytics system.');